<?php
/**
 * Functions.php contains all the core functions for your theme to work properly.
 * Please do not edit this file!!
 *
 * @package Thoughts WordPress Theme
 */

defined( 'ABSPATH' ) || exit;

// Define Constants
define( 'WPEX_JS_DIR', get_template_directory_uri() . '/js' );
define( 'WPEX_CSS_DIR', get_template_directory_uri() . '/css' );

// Theme Setup
if ( ! function_exists( 'wpex_setup' ) ) {
	function wpex_setup() {

		$content_width = 945;

		// Theme support
		add_theme_support( 'automatic-feed-links' );
		add_theme_support( 'custom-background' );
		add_theme_support( 'post-thumbnails' );
		add_theme_support( 'title-tag' );

		//register navigation menus.
		register_nav_menus( array(
			'main_menu' => esc_html__( 'Main Menu', 'wpex-thoughts' )
		) );

		// Add Post Formats Support.
		add_theme_support( 'post-formats', array( 'video', 'quote', 'link', 'audio', 'image', 'gallery' ) );

		//Localization support.
		load_theme_textdomain( 'wpex-thoughts', get_template_directory() . '/languages' );

	}
}
add_action( 'after_setup_theme', 'wpex_setup' );

// Get template directory.
$template_dir = get_template_directory();

// Includes.
require_once $template_dir . '/functions/scripts.php';
require_once $template_dir . '/functions/hooks.php';
require_once $template_dir . '/functions/theme_customizer.php';
require_once $template_dir . '/functions/pagination.php';
require_once $template_dir . '/functions/img_resizer.php';
require_once $template_dir . '/functions/img_defaults.php';
require_once $template_dir . '/functions/wpex_comments_output.php';
require_once $template_dir . '/functions/gallery.php';

if ( is_admin() ) {
	require_once $template_dir . '/lib/gallery-metabox/gallery-metabox.php';
	require_once $template_dir . '/functions/post_meta.php';
	require_once $template_dir . '/functions/welcome.php';
}

// Title attribute.
function wpex_the_title_attribute( $post = '' ) {
	return the_title_attribute( array(
		'echo' => true,
		'post' => $post,
	) );
}

// Change default read more style
if ( ! function_exists( 'wpex_new_excerpt_more' ) ) {
	function wpex_new_excerpt_more( $more ) {
		return '...';
	}
}
add_filter( 'excerpt_more', 'wpex_new_excerpt_more' );

// Change default excerpt length
if ( ! function_exists( 'wpex_custom_excerpt_length' ) ) {
	function wpex_custom_excerpt_length( $length ) {
		return get_theme_mod( 'wpex_excerpt_length', '100' );
	}
}
add_filter( 'excerpt_length', 'wpex_custom_excerpt_length', 999 );